name: flutter_instaclone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  image_picker: any
  logger: any
  dotted_border: ^2.0.0+2
  fluttertoast: any
  hive: any
  hive_flutter: any
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  cloud_firestore: any
  provider: ^6.0.2

  cached_network_image: ^3.2.0
  firebase_messaging: ^11.2.11
  device_info_plus: ^3.2.2
  flutter_local_notifications: ^9.4.0
  flutter_styled_toast: ^2.0.0
  http: ^0.13.4
  path_provider: ^2.0.9
  share_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/icons/
    - assets/splash_page/
    - assets/profile_pictures/


  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/FontsFree-Net-Billabong.ttf
    - family: instagramFont
      fonts:
        - asset: assets/fonts/instagramFont.otf
