name: flutter_instaclone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  image_picker: any
  logger: any
  dotted_border: ^2.0.0+2
  fluttertoast: any
  hive: any
  hive_flutter: any
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  cloud_firestore: any
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/FontsFree-Net-Billabong.ttf
